config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :comments
  devise_for :users
  get 'pages/info'
 get 'pages/doadoras'

  resources :pensamentos

root to: redirect('/pensamentos')
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :pensamento
end

app/models/pensamento.rb
class Pensamento < ApplicationRecord
	has_many :comments
	mount_uploader :picture, PictureUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         include Gravtastic
		gravtastic
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
   before_action :authenticate_user!
   before_action :configure_permitted_parameters, if: :devise_controller?
protected
def configure_permitted_parameters
 devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
 devise_parameter_sanitizer.permit(:sign_in, keys: [:username])
 devise_parameter_sanitizer.permit(:account_update, keys: [:username])
end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @comment, notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:user_name, :body, :pensamento_id)
    end
end

app/controllers/doadoras_controller.rb
class DoadorasController < ApplicationController
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def info
  end
end

app/controllers/pensamentos_controller.rb
class PensamentosController < ApplicationController
  before_action :set_pensamento, only: [:show, :edit, :update, :destroy]

  # GET /pensamentos
  # GET /pensamentos.json
  def index
    @pensamentos = Pensamento.all
  end

  # GET /pensamentos/1
  # GET /pensamentos/1.json
  def show
    @comments = @pensamento.comments.all
    @comment = @pensamento.comments.build
  end

  # GET /pensamentos/new
  def new
    @pensamento = Pensamento.new
  end

  # GET /pensamentos/1/edit
  def edit
  end

  # POST /pensamentos
  # POST /pensamentos.json
  def create
    @pensamento = Pensamento.new(pensamento_params)

    respond_to do |format|
      if @pensamento.save
        format.html { redirect_to @pensamento, notice: 'Pensamento was successfully created.' }
        format.json { render :show, status: :created, location: @pensamento }
      else
        format.html { render :new }
        format.json { render json: @pensamento.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pensamentos/1
  # PATCH/PUT /pensamentos/1.json
  def update
    respond_to do |format|
      if @pensamento.update(pensamento_params)
        format.html { redirect_to @pensamento, notice: 'Pensamento was successfully updated.' }
        format.json { render :show, status: :ok, location: @pensamento }
      else
        format.html { render :edit }
        format.json { render json: @pensamento.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pensamentos/1
  # DELETE /pensamentos/1.json
  def destroy
    @pensamento.destroy
    respond_to do |format|
      format.html { redirect_to pensamentos_url, notice: 'Pensamento was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pensamento
      @pensamento = Pensamento.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pensamento_params
      params.require(:pensamento).permit(:name, :description, :picture)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/doadoras_helper.rb
module DoadorasHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pensamentos_helper.rb
module PensamentosHelper
end

app/views/comments/_form.html.erb
<%= form_with(model: comment, local: true) do |form| %>
  <% if comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_name %>
    <%= form.text_field :user_name, id: :comment_user_name %>
  </div>


  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body, id: :comment_body %>
  </div>
  <%= form.hidden_field :pensamento_id %>

  

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Comments</h1>

<table>
  <thead>
    <tr>
      <th>User name</th>
      <th>Body</th>
      <th>Pensamento</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.user_name %></td>
        <td><%= comment.body %></td>
        <td><%= comment.pensamento_id %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User name:</strong>
  <%= @comment.user_name %>
</p>

<p>
  <strong>Body:</strong>
  <%= @comment.body %>
</p>

<p>
  <strong>Pensamento:</strong>
  <%= @comment.pensamento_id %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Breastfeeding Friends</title>
    <%= csrf_meta_tags %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<nav class="navbar navbar-expand-lg navbar-sucess" >
  <div class="container">
    <a class="navbar-brand" href="/" style="color: #fdfdfd ">Breastfeeding Friends</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
        <a class="nav-link" href="/pages/info" style="color: #fdfdfd ">Info</a>
        </li>

        <li class="nav-item active">
          <a class="nav-link" href="/pensamentos" style="color: #fdfdfd">Pensamentos</a>
        </li>
        <li class="nav-item active">
          <a class="nav-link" href ="/pages/doadoras" style="color: #fdfdfd">Doadoras</a>
        </li>
      </ul>

      <p class="navbar-text float-right" style="color: #fdfdfd ">
<% if user_signed_in? %>
  Logado como: <strong><%= current_user.username %></strong>.
  <%= link_to 'Editar perfil', edit_user_registration_path, :class => 'navbar-link' %> |
  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
  <%= image_tag current_user.gravatar_url, :class => "gravatar" %>
<% else %>
  <%= link_to "Registrar-se", new_user_registration_path, :class => 'navbar-link'  %> |
  <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
<% end %>
    </div>
  </div>
</nav>

   <div class="container">
    <% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>
  	<%= yield %>
  </div>

  <footer>
  <div class="container" color: #fdfdfd >
  Breastfeeding Friends <%= Time.now.year %>
  </div>
</footer>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>
  </body>
</html>

app/views/pages/doadoras.html.erb
<h1>Doadoras</h1>
<br>
<h3>Mariana Sampaio</h3>
<img src="/mulher5.png" alt="Foto de perfil" width="70px" height="70px" >
<p>"Mãe de leite de primeira viagem, mas com muita vontade de ajudar"</p>
<p>Contatos : e-mail- marianasampaio@gmail.com | telefone:998875642  </p>
<h4>Prontuário Médico</h4>
<img src="/prontuario.png" alt="Prontuário" width="140px" height="140px">
<img>
<br>
<h3>Suely Pedrosa</h3>
<img src="mulher2.png" >
<p>"Acabei perdendo meu bebê, mas tenho certeza que tudo teve um propósito"</p>
<p>Contatos : suelypredrosa@gmail.com | telefone:999995555 </p>
<h4>Prontuário Médico</h4>
<img src="/prontuario.png" alt="Prontuário" width="140px" height="140px">
<img>
<br>
<h3>Lia Menezes</h3>
<img src="mulher7.png" >
<p>"Mãe de leite experiente"</p>
<p>Contatos : liamenezes@gmail.com | telefone:988887777</p>
<h4>Prontuário Médico</h4>
<img src="/prontuario.png" alt="Prontuário" width="140px" height="140px">
<img>
<br>
<h3>Tatiana Sousa</h3>
<img src="mulher10.png" >
<p>"Assim posso ajudar um pouco os outros"</p>
<p>Contatos : tatianasousa@gmail.com | telefone:955557777</p>
<h4>Prontuário Médico</h4>
<img src="/prontuario.png" alt="Prontuário" width="140px" height="140px">
<img>
<br>
<h3>Paula Queiroz</h3>
<img src="mulher8.png" >
<p>"Minha mãe era mãe de leite, agora é a minha vez de contribuir"</p>
<p>Contatos : pailaqueiroz@gmail.com | telefone:958746325 </p>
<h4>Prontuário Médico</h4>
<img src="/prontuario.png" alt="Prontuário" width="140px" height="140px">
<img>
<br>

app/views/pages/info.html.erb
<h1>Quem somos</h1>
<p>Estudantes de Engenharia de Software e de Engenharia Aeroespacial, adeptas da ideia de que toda criança tem o direito de amamentação, tendo mãe ou não,seja em um local público ou não. </p>

app/views/pensamentos/_form.html.erb
<%= form_with(model: pensamento, local: true) do |form| %>
  <% if pensamento.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pensamento.errors.count, "error") %> prohibited this pensamento from being saved:</h2>

      <ul>
      <% pensamento.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :pensamento_name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, id: :pensamento_description %>
  </div>

  <div class="field">
    <%= form.label :picture %>
    <%= form.file_field :picture %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/pensamentos/edit.html.erb
<h1>Editing Pensamento</h1>

<%= render 'form', pensamento: @pensamento %>

<%= link_to 'Show', @pensamento %> |
<%= link_to 'Back', pensamentos_path %>

app/views/pensamentos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Pensamentos</h1>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Picture</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pensamentos.each do |pensamento| %>
      <tr>
        <td><%= pensamento.name %></td>
        <td><%= pensamento.description %></td>
        <td><%= image_tag(pensamento.picture_url, :width => 300) if pensamento.picture.present? %></td>
        <td><%= link_to 'Show', pensamento %></td>
        <td><%= link_to 'Edit', edit_pensamento_path(pensamento) %></td>
        <td><%= link_to 'Destroy', pensamento, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pensamento', new_pensamento_path %>

app/views/pensamentos/new.html.erb
<h1>New Pensamento</h1>

<%= render 'form', pensamento: @pensamento %>

<%= link_to 'Back', pensamentos_path %>

app/views/pensamentos/show.html.erb
 

<p>
  <strong>Name:</strong>
  <%= @pensamento.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @pensamento.description %>
</p>

<p>
  <strong>Picture:</strong>
  <%= image_tag(@pensamento.picture_url, width: 600) if @pensamento.picture.present? %>

  <h3>Comentários</h3>
<% @comments.each do |comment| %>
  <div>
    <strong><%= comment.user_name %></strong>
    <br>
    <p><%= comment.body %></p>
    <p><%= link_to 'Delete', comment_path(comment), method: :delete, data: { confirm: 'Tem certeza?' } %></p>
  </div>
<% end %>
<%= render partial: 'comments/form', locals: { comment: @comment } %>
</p>

<%= link_to 'Edit', edit_pensamento_path(@pensamento) %> |
<%= link_to 'Back', pensamentos_path %>

app/views/pensamentosAdm/_form.html.erb
<%= form_with(model: pensamento, local: true) do |form| %>
  <% if pensamento.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pensamento.errors.count, "error") %> prohibited this pensamento from being saved:</h2>

      <ul>
      <% pensamento.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :pensamento_name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, id: :pensamento_description %>
  </div>

  <div class="field">
    <%= form.label :picture %>
    <%= form.file_field :picture %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/pensamentosAdm/edit.html.erb
<h1>Editing Pensamento</h1>

<%= render 'form', pensamento: @pensamento %>

<%= link_to 'Show', @pensamento %> |
<%= link_to 'Back', pensamentos_path %>

app/views/pensamentosAdm/index.html.erb
 

<h1>Doadoras</h1>

<table class="table">
  <thead>
    <tr>
      <th>Doadora</th>
      <th>Dados</th>
      <th>Prontuario</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pensamentos.each do |pensamento| %>
      <tr>
        <td><%= pensamento.name %></td>
        <td><%= pensamento.description %></td>
        <td><%= image_tag(pensamento.picture_url, :width => 400) if pensamento.picture.present? %></td>
        <td><%= link_to 'Show', pensamento %></td>
        <td><%= link_to 'Edit', edit_pensamento_path(pensamento) %></td>
        <td><%= link_to 'Destroy', pensamento, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pensamento', new_pensamento_path %>

app/views/pensamentosAdm/new.html.erb
<h1>New Pensamento</h1>

<%= render 'form', pensamento: @pensamento %>

<%= link_to 'Back', pensamentos_path %>

app/views/pensamentosAdm/show.html.erb
 

<p>
  <strong>Name:</strong>
  <%= @pensamento.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @pensamento.description %>
</p>

<p>
  <strong>Picture:</strong>
  <%= image_tag(@pensamento.picture_url, width: 600) if @pensamento.picture.present? %>

  <h3>Comentários</h3>
<% @comments.each do |comment| %>
  <div>
    <strong><%= comment.user_name %></strong>
    <br>
    <p><%= comment.body %></p>
    <p><%= link_to 'Delete', comment_path(comment), method: :delete, data: { confirm: 'Tem certeza?' } %></p>
  </div>
<% end %>
<%= render partial: 'comments/form', locals: { comment: @comment } %>
</p>

<%= link_to 'Edit', edit_pensamento_path(@pensamento) %> |
<%= link_to 'Back', pensamentos_path %>